-- Удаление таблицы и индекса, если они уже существуют
DROP TABLE IF EXISTS public.student CASCADE;
DROP INDEX IF EXISTS student_pkey;

-- Создание таблицы student с PRIMARY KEY, который автоматически создаст индекс
CREATE TABLE public.student (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name VARCHAR(255) COLLATE pg_catalog."default"
);

-- Установить владельца таблицы
ALTER TABLE public.student
    OWNER TO neverkoa;
