-- Создание таблицы student с PRIMARY KEY, который автоматически создаст индекс
create table if not exists student
(
    id      bigint generated by default as identity
        primary key,
    name    varchar(255),
    surname varchar(255)
);
-- Установить владельца таблицы
alter table student
    owner to neverkoa;